== Java 9 Workshop Requirements

1) First of all bring your laptop :), or share one with your mate.

2) Install JDK 9+ by your OS. You can download current version (JDK 10) here http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html

Be sure that *java* and *javac* commands are accessible on command prompt.

[source,bash]
----
java -version <1>

java version "10.0.1" 2018-04-17 <2>
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
----
<1> Check java version
<2> Be sure you have 9+

[source,bash]
----
javac -version <1>

javac 10.0.1 <2>
----
<1> Check javac version
<2> Be sure you have 9+

[CAUTION]
====
I saw in the previous practices, some attendees checked `java -version` but not `javac -version`. Be sure that both print 9+ version.
====

3) Set JAVA_HOME system variable

Set JAVA_HOME system variable properly or use direct path where it is used. We use it in the generate-image scripts.

3) Your favorite text editor

Sublime, Atom, Notepad++, or any that you are comfortable with it. Some examples includes maven projects, but you don't need to install maven thanks to the maven wrapper.

4) Watch the repository so you will be notified with repository updates ;)

5) Any contribution is welcomed, don't be shy for pull requests :)

See you!
Rahman
